// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: room.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_room_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_room_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_room_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_room_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_room_2eproto;
namespace proto {
class EnterRoomRequest;
class EnterRoomRequestDefaultTypeInternal;
extern EnterRoomRequestDefaultTypeInternal _EnterRoomRequest_default_instance_;
class EnterRoomResponse;
class EnterRoomResponseDefaultTypeInternal;
extern EnterRoomResponseDefaultTypeInternal _EnterRoomResponse_default_instance_;
class ReadyNotify;
class ReadyNotifyDefaultTypeInternal;
extern ReadyNotifyDefaultTypeInternal _ReadyNotify_default_instance_;
class ReadyRequest;
class ReadyRequestDefaultTypeInternal;
extern ReadyRequestDefaultTypeInternal _ReadyRequest_default_instance_;
class RoomStateNotify;
class RoomStateNotifyDefaultTypeInternal;
extern RoomStateNotifyDefaultTypeInternal _RoomStateNotify_default_instance_;
}  // namespace proto
PROTOBUF_NAMESPACE_OPEN
template<> ::proto::EnterRoomRequest* Arena::CreateMaybeMessage<::proto::EnterRoomRequest>(Arena*);
template<> ::proto::EnterRoomResponse* Arena::CreateMaybeMessage<::proto::EnterRoomResponse>(Arena*);
template<> ::proto::ReadyNotify* Arena::CreateMaybeMessage<::proto::ReadyNotify>(Arena*);
template<> ::proto::ReadyRequest* Arena::CreateMaybeMessage<::proto::ReadyRequest>(Arena*);
template<> ::proto::RoomStateNotify* Arena::CreateMaybeMessage<::proto::RoomStateNotify>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace proto {

// ===================================================================

class EnterRoomRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.EnterRoomRequest) */ {
 public:
  inline EnterRoomRequest() : EnterRoomRequest(nullptr) {};
  virtual ~EnterRoomRequest();

  EnterRoomRequest(const EnterRoomRequest& from);
  EnterRoomRequest(EnterRoomRequest&& from) noexcept
    : EnterRoomRequest() {
    *this = ::std::move(from);
  }

  inline EnterRoomRequest& operator=(const EnterRoomRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnterRoomRequest& operator=(EnterRoomRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EnterRoomRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EnterRoomRequest* internal_default_instance() {
    return reinterpret_cast<const EnterRoomRequest*>(
               &_EnterRoomRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EnterRoomRequest& a, EnterRoomRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(EnterRoomRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnterRoomRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EnterRoomRequest* New() const final {
    return CreateMaybeMessage<EnterRoomRequest>(nullptr);
  }

  EnterRoomRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EnterRoomRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EnterRoomRequest& from);
  void MergeFrom(const EnterRoomRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EnterRoomRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.EnterRoomRequest";
  }
  protected:
  explicit EnterRoomRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_room_2eproto);
    return ::descriptor_table_room_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoomIdFieldNumber = 1,
  };
  // int64 room_id = 1;
  void clear_room_id();
  ::PROTOBUF_NAMESPACE_ID::int64 room_id() const;
  void set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_room_id() const;
  void _internal_set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:proto.EnterRoomRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int64 room_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_room_2eproto;
};
// -------------------------------------------------------------------

class EnterRoomResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.EnterRoomResponse) */ {
 public:
  inline EnterRoomResponse() : EnterRoomResponse(nullptr) {};
  virtual ~EnterRoomResponse();

  EnterRoomResponse(const EnterRoomResponse& from);
  EnterRoomResponse(EnterRoomResponse&& from) noexcept
    : EnterRoomResponse() {
    *this = ::std::move(from);
  }

  inline EnterRoomResponse& operator=(const EnterRoomResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnterRoomResponse& operator=(EnterRoomResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const EnterRoomResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EnterRoomResponse* internal_default_instance() {
    return reinterpret_cast<const EnterRoomResponse*>(
               &_EnterRoomResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(EnterRoomResponse& a, EnterRoomResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(EnterRoomResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnterRoomResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline EnterRoomResponse* New() const final {
    return CreateMaybeMessage<EnterRoomResponse>(nullptr);
  }

  EnterRoomResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<EnterRoomResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const EnterRoomResponse& from);
  void MergeFrom(const EnterRoomResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EnterRoomResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.EnterRoomResponse";
  }
  protected:
  explicit EnterRoomResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_room_2eproto);
    return ::descriptor_table_room_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRoomIdFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // int64 room_id = 2;
  void clear_room_id();
  ::PROTOBUF_NAMESPACE_ID::int64 room_id() const;
  void set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_room_id() const;
  void _internal_set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 code = 1;
  void clear_code();
  ::PROTOBUF_NAMESPACE_ID::int32 code() const;
  void set_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_code() const;
  void _internal_set_code(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:proto.EnterRoomResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int64 room_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 code_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_room_2eproto;
};
// -------------------------------------------------------------------

class ReadyRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.ReadyRequest) */ {
 public:
  inline ReadyRequest() : ReadyRequest(nullptr) {};
  virtual ~ReadyRequest();

  ReadyRequest(const ReadyRequest& from);
  ReadyRequest(ReadyRequest&& from) noexcept
    : ReadyRequest() {
    *this = ::std::move(from);
  }

  inline ReadyRequest& operator=(const ReadyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReadyRequest& operator=(ReadyRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReadyRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadyRequest* internal_default_instance() {
    return reinterpret_cast<const ReadyRequest*>(
               &_ReadyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ReadyRequest& a, ReadyRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ReadyRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReadyRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReadyRequest* New() const final {
    return CreateMaybeMessage<ReadyRequest>(nullptr);
  }

  ReadyRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReadyRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReadyRequest& from);
  void MergeFrom(const ReadyRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadyRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.ReadyRequest";
  }
  protected:
  explicit ReadyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_room_2eproto);
    return ::descriptor_table_room_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReadyFieldNumber = 1,
  };
  // bool ready = 1;
  void clear_ready();
  bool ready() const;
  void set_ready(bool value);
  private:
  bool _internal_ready() const;
  void _internal_set_ready(bool value);
  public:

  // @@protoc_insertion_point(class_scope:proto.ReadyRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool ready_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_room_2eproto;
};
// -------------------------------------------------------------------

class ReadyNotify PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.ReadyNotify) */ {
 public:
  inline ReadyNotify() : ReadyNotify(nullptr) {};
  virtual ~ReadyNotify();

  ReadyNotify(const ReadyNotify& from);
  ReadyNotify(ReadyNotify&& from) noexcept
    : ReadyNotify() {
    *this = ::std::move(from);
  }

  inline ReadyNotify& operator=(const ReadyNotify& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReadyNotify& operator=(ReadyNotify&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReadyNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReadyNotify* internal_default_instance() {
    return reinterpret_cast<const ReadyNotify*>(
               &_ReadyNotify_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ReadyNotify& a, ReadyNotify& b) {
    a.Swap(&b);
  }
  inline void Swap(ReadyNotify* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReadyNotify* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReadyNotify* New() const final {
    return CreateMaybeMessage<ReadyNotify>(nullptr);
  }

  ReadyNotify* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReadyNotify>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReadyNotify& from);
  void MergeFrom(const ReadyNotify& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadyNotify* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.ReadyNotify";
  }
  protected:
  explicit ReadyNotify(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_room_2eproto);
    return ::descriptor_table_room_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kReadyFieldNumber = 2,
  };
  // int64 player_id = 1;
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::int64 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // bool ready = 2;
  void clear_ready();
  bool ready() const;
  void set_ready(bool value);
  private:
  bool _internal_ready() const;
  void _internal_set_ready(bool value);
  public:

  // @@protoc_insertion_point(class_scope:proto.ReadyNotify)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int64 player_id_;
  bool ready_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_room_2eproto;
};
// -------------------------------------------------------------------

class RoomStateNotify PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:proto.RoomStateNotify) */ {
 public:
  inline RoomStateNotify() : RoomStateNotify(nullptr) {};
  virtual ~RoomStateNotify();

  RoomStateNotify(const RoomStateNotify& from);
  RoomStateNotify(RoomStateNotify&& from) noexcept
    : RoomStateNotify() {
    *this = ::std::move(from);
  }

  inline RoomStateNotify& operator=(const RoomStateNotify& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoomStateNotify& operator=(RoomStateNotify&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RoomStateNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoomStateNotify* internal_default_instance() {
    return reinterpret_cast<const RoomStateNotify*>(
               &_RoomStateNotify_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RoomStateNotify& a, RoomStateNotify& b) {
    a.Swap(&b);
  }
  inline void Swap(RoomStateNotify* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoomStateNotify* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RoomStateNotify* New() const final {
    return CreateMaybeMessage<RoomStateNotify>(nullptr);
  }

  RoomStateNotify* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RoomStateNotify>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RoomStateNotify& from);
  void MergeFrom(const RoomStateNotify& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoomStateNotify* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "proto.RoomStateNotify";
  }
  protected:
  explicit RoomStateNotify(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_room_2eproto);
    return ::descriptor_table_room_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdsFieldNumber = 3,
    kRoomIdFieldNumber = 1,
    kStateFieldNumber = 2,
  };
  // repeated int64 player_ids = 3;
  int player_ids_size() const;
  private:
  int _internal_player_ids_size() const;
  public:
  void clear_player_ids();
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_player_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      _internal_player_ids() const;
  void _internal_add_player_ids(::PROTOBUF_NAMESPACE_ID::int64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      _internal_mutable_player_ids();
  public:
  ::PROTOBUF_NAMESPACE_ID::int64 player_ids(int index) const;
  void set_player_ids(int index, ::PROTOBUF_NAMESPACE_ID::int64 value);
  void add_player_ids(::PROTOBUF_NAMESPACE_ID::int64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      player_ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_player_ids();

  // int64 room_id = 1;
  void clear_room_id();
  ::PROTOBUF_NAMESPACE_ID::int64 room_id() const;
  void set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_room_id() const;
  void _internal_set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 state = 2;
  void clear_state();
  ::PROTOBUF_NAMESPACE_ID::int32 state() const;
  void set_state(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_state() const;
  void _internal_set_state(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:proto.RoomStateNotify)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 > player_ids_;
  mutable std::atomic<int> _player_ids_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::int64 room_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_room_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EnterRoomRequest

// int64 room_id = 1;
inline void EnterRoomRequest::clear_room_id() {
  room_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EnterRoomRequest::_internal_room_id() const {
  return room_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EnterRoomRequest::room_id() const {
  // @@protoc_insertion_point(field_get:proto.EnterRoomRequest.room_id)
  return _internal_room_id();
}
inline void EnterRoomRequest::_internal_set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  room_id_ = value;
}
inline void EnterRoomRequest::set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_room_id(value);
  // @@protoc_insertion_point(field_set:proto.EnterRoomRequest.room_id)
}

// -------------------------------------------------------------------

// EnterRoomResponse

// int32 code = 1;
inline void EnterRoomResponse::clear_code() {
  code_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EnterRoomResponse::_internal_code() const {
  return code_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 EnterRoomResponse::code() const {
  // @@protoc_insertion_point(field_get:proto.EnterRoomResponse.code)
  return _internal_code();
}
inline void EnterRoomResponse::_internal_set_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  code_ = value;
}
inline void EnterRoomResponse::set_code(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:proto.EnterRoomResponse.code)
}

// int64 room_id = 2;
inline void EnterRoomResponse::clear_room_id() {
  room_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EnterRoomResponse::_internal_room_id() const {
  return room_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 EnterRoomResponse::room_id() const {
  // @@protoc_insertion_point(field_get:proto.EnterRoomResponse.room_id)
  return _internal_room_id();
}
inline void EnterRoomResponse::_internal_set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  room_id_ = value;
}
inline void EnterRoomResponse::set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_room_id(value);
  // @@protoc_insertion_point(field_set:proto.EnterRoomResponse.room_id)
}

// -------------------------------------------------------------------

// ReadyRequest

// bool ready = 1;
inline void ReadyRequest::clear_ready() {
  ready_ = false;
}
inline bool ReadyRequest::_internal_ready() const {
  return ready_;
}
inline bool ReadyRequest::ready() const {
  // @@protoc_insertion_point(field_get:proto.ReadyRequest.ready)
  return _internal_ready();
}
inline void ReadyRequest::_internal_set_ready(bool value) {
  
  ready_ = value;
}
inline void ReadyRequest::set_ready(bool value) {
  _internal_set_ready(value);
  // @@protoc_insertion_point(field_set:proto.ReadyRequest.ready)
}

// -------------------------------------------------------------------

// ReadyNotify

// int64 player_id = 1;
inline void ReadyNotify::clear_player_id() {
  player_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ReadyNotify::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 ReadyNotify::player_id() const {
  // @@protoc_insertion_point(field_get:proto.ReadyNotify.player_id)
  return _internal_player_id();
}
inline void ReadyNotify::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  player_id_ = value;
}
inline void ReadyNotify::set_player_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:proto.ReadyNotify.player_id)
}

// bool ready = 2;
inline void ReadyNotify::clear_ready() {
  ready_ = false;
}
inline bool ReadyNotify::_internal_ready() const {
  return ready_;
}
inline bool ReadyNotify::ready() const {
  // @@protoc_insertion_point(field_get:proto.ReadyNotify.ready)
  return _internal_ready();
}
inline void ReadyNotify::_internal_set_ready(bool value) {
  
  ready_ = value;
}
inline void ReadyNotify::set_ready(bool value) {
  _internal_set_ready(value);
  // @@protoc_insertion_point(field_set:proto.ReadyNotify.ready)
}

// -------------------------------------------------------------------

// RoomStateNotify

// int64 room_id = 1;
inline void RoomStateNotify::clear_room_id() {
  room_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RoomStateNotify::_internal_room_id() const {
  return room_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RoomStateNotify::room_id() const {
  // @@protoc_insertion_point(field_get:proto.RoomStateNotify.room_id)
  return _internal_room_id();
}
inline void RoomStateNotify::_internal_set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  room_id_ = value;
}
inline void RoomStateNotify::set_room_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_room_id(value);
  // @@protoc_insertion_point(field_set:proto.RoomStateNotify.room_id)
}

// int32 state = 2;
inline void RoomStateNotify::clear_state() {
  state_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomStateNotify::_internal_state() const {
  return state_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomStateNotify::state() const {
  // @@protoc_insertion_point(field_get:proto.RoomStateNotify.state)
  return _internal_state();
}
inline void RoomStateNotify::_internal_set_state(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  state_ = value;
}
inline void RoomStateNotify::set_state(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:proto.RoomStateNotify.state)
}

// repeated int64 player_ids = 3;
inline int RoomStateNotify::_internal_player_ids_size() const {
  return player_ids_.size();
}
inline int RoomStateNotify::player_ids_size() const {
  return _internal_player_ids_size();
}
inline void RoomStateNotify::clear_player_ids() {
  player_ids_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RoomStateNotify::_internal_player_ids(int index) const {
  return player_ids_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RoomStateNotify::player_ids(int index) const {
  // @@protoc_insertion_point(field_get:proto.RoomStateNotify.player_ids)
  return _internal_player_ids(index);
}
inline void RoomStateNotify::set_player_ids(int index, ::PROTOBUF_NAMESPACE_ID::int64 value) {
  player_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto.RoomStateNotify.player_ids)
}
inline void RoomStateNotify::_internal_add_player_ids(::PROTOBUF_NAMESPACE_ID::int64 value) {
  player_ids_.Add(value);
}
inline void RoomStateNotify::add_player_ids(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_add_player_ids(value);
  // @@protoc_insertion_point(field_add:proto.RoomStateNotify.player_ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
RoomStateNotify::_internal_player_ids() const {
  return player_ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
RoomStateNotify::player_ids() const {
  // @@protoc_insertion_point(field_list:proto.RoomStateNotify.player_ids)
  return _internal_player_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
RoomStateNotify::_internal_mutable_player_ids() {
  return &player_ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
RoomStateNotify::mutable_player_ids() {
  // @@protoc_insertion_point(field_mutable_list:proto.RoomStateNotify.player_ids)
  return _internal_mutable_player_ids();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_room_2eproto
